### ISSUE TITLE
Error running app from icon only

### ISSUE THREAD

**Issue by jsigee87** [UTNuclearRoboticsPublic/project-crunch#25]
Was still getting environment variable issue with launcher. Double checked environment variables exist, cloned fresh copy of repo, no issues from command line with `fbs run`. No issues from command line running executable. Running executable from the icon returns same error message as before, although it should not.

Also restarted the computer, printed out envs to make sure they are being read by os, and verified the issue persists whether you run from the symlink or the actual binary. This could be an fbs issue.

![image](https://user-images.githubusercontent.com/22483938/55987451-3873a280-5c67-11e9-963f-2f4233828d73.png)

**Comment by danieldiamont** [comment]
The problem is that environment variables for the graphical X11 session (Unity) are not set using the `.bashrc`. Rather, the environment variable export statements must be placed in a file called `.xsessionrc` which runs whenever an X11 session begins.

The issue and solution is documented here.
[https://askubuntu.com/questions/82120/how-do-i-set-an-environment-variable-in-a-unity-session](url)

More info on `.xsessionrc` and X11 Window system.
[https://unix.stackexchange.com/questions/281858/difference-between-xinitrc-xsession-and-xsessionrc](url)

**Action Items:**

Add parallel export statements to `.xsessionrc` next to the original `.bashrc` export statements.
